title: Luber Lab Journal Club
description: LLM and Multimodal Vision/Pathology Research
baseurl: "/luberlab-jc-fall24"
url: "https://facevoid.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
